### ISSUE TITLE
I'm having problems to run the executable.

### ISSUE THREAD

**Issue by NautilusOcean** [hayachan19/RedguardUI#1]
Hey

How am I supposed to run the exe, just double-click on the exe? Use it with my cmd? I need to use it on an old Windows 98 OS or I can run it on Windows 10?

I installed .NET Core but it still don't work (yes I put the files on the main directory).

Btw seems to be an interesting project, I'm a big fan of redguard and now there's even an mod manager with a texture viewer (can even export and import textures) by a guy called Dillonn241, he is an UESP Editor too.
Good day.

**Comment by hayachan19** [comment]
I suppose the readme isn't thorough enough (just the essential info to call it a day).

This program is meant to be used as a replacement for settings portion of the original launcher, with primary use-case being the GOG version of the game which doesn't ship with it, not to mention it wouldn't work due to missing registry keys. Not exactly a drop-in, but having easy access to game settings not available in-game was the main goal.

The launcher looks for SYSTEM.INI and DIG.INI files in the working directory, and quietly fails when they cannot be found... Not the best programming practice and I was fully aware of it. Time to pay for my laziness...

I'll add error handling for startup process ASAP and do some auditing while at it, as well as improve the readme to address any ambiguity.

Thank you for finding interest in my work.

**Comment by hayachan19** [comment]
v1.0.1 is out and supersedes the original release, which due to packaging misunderstanding was unrunnable (.NET Core needs `runtimeconfig.json` to be in the working directory, otherwise it keeps nagging about installing the runtime, lessons learned).
